# Generated by Django 2.2.15 on 2020-08-07 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact1', models.CharField(blank=True, max_length=30, null=True)),
                ('contact2', models.CharField(blank=True, max_length=30, null=True)),
                ('birth', models.FileField(blank=True, null=True, upload_to='%s/birth/')),
                ('naid', models.FileField(blank=True, null=True, upload_to='%s/naid/')),
                ('letter', models.FileField(blank=True, null=True, upload_to='%s/letter/')),
                ('school', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('sponsored', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
