# Generated by Django 2.2.15 on 2020-08-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_auto_20200807_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='names',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
