# Generated by Django 2.2.15 on 2020-08-08 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholarship_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
